version: '3.8'
services:
  backend_service_voice_ai:
    build:
      context: ./backend_service  # Путь к директории, содержащей Dockerfile
      dockerfile: Dockerfile      # Имя Dockerfile, если оно отличается от стандартного
    ports:
      - "8765:8765"
    container_name: backend_service_voice_ai
    pull_policy: always
    tty: true
    restart: always
    networks:
      - ollama-docker

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    runtime: nvidia # Activ GPU
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    networks:
      - ollama-docker

networks:
  ollama-docker:
    external: false
